### ISSUE TITLE
OverlayFS

### ISSUE THREAD

**Issue by Kivutar** [kszaq/OpenELEC.tv#34]
Hello, I'm trying to apply this patch to your S805 kernel : https://github.com/adilinden/overlayfs-patches/blob/master/overlayfs.v18-3.10-rc7.patch 

The patch applies, but vmlinux fails to build.

I get a

    undefined reference to `vfs_readdir'

I replaced all occurences of vfs_readdir with the new iterate_dir but it still fails to build.

The same patch works well on other 3.10 kernels like the one of WeTek_Play and WeTek_Core.

Where did you get the S805 kernel?

**Comment by kszaq** [comment]
Hi. Here's my kernel source: https://github.com/kszaq/linux

It's the same kernel WeTek uses with some additional patches.

I applied the patch you linked and kernel builds fine for me with `CONFIG_OVERLAYFS_FS=m` in config.

**Comment by Kivutar** [comment]
Thanks, I'm building from your LibreELEC repo, so maybe there is a difference? (It shouldn't build since vfs_readdir have been deprecated)

**Comment by kszaq** [comment]
Actually I applied the patch to my LE build. And it builds fine.

**Comment by Kivutar** [comment]
Oh, It builds fine with `CONFIG_OVERLAYFS_FS=m` but not with `CONFIG_OVERLAYFS_FS=y` !

**Comment by kszaq** [comment]
You can try cherry-picking overlayfs patches from endlessm kernel: https://github.com/endlessm/linux-meson/commits/master/fs

**Comment by Kivutar** [comment]
Ah yes, thanks a lot

**Comment by kszaq** [comment]
https://github.com/kszaq/linux/tree/overlayfs

**Comment by Kivutar** [comment]
Thanks a lot @kszaq 

I try it right now.

Does it build for you?

**Comment by Kivutar** [comment]
Ok, got it working by applying this https://github.com/endlessm/linux-meson/commit/2b5daffa58d353d80d992debd54a02c892e32b86 and this https://github.com/endlessm/linux-meson/commit/ff2e802e96f11a8d94025ab23df98f445d114aa9 on top of your branch.

Thanks for your precious help.
